(setq completion-ignore-case t)
(setq create-lockfiles nil)
(setq display-buffer-alist '((".*" (display-buffer-reuse-window display-buffer-same-window))))
(setq frame-inhibit-implied-resize t)
(setq indicate-buffer-boundaries 'right)
(setq initial-scratch-message "")
(setq mouse-autoselect-window t)
(setq network-security-level 'paranoid)
(setq package-enable-at-startup nil)
(setq enable-recursive-minibuffers t)
(setq tab-always-indent 'complete)
(setq visible-bell t)

(setq-default fill-column 100)
(setq-default frame-title-format '("%n %b - %F"))
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)

(put 'narrow-to-region 'disabled nil)

(menu-bar-mode 0)
(tool-bar-mode 0)
